[server]
headless = true
enableCORS = false
enableWebsocketCompression = false

[theme]
wideMode = true
primaryColor = "#774BFF"
backgroundColor = "#0E1117"
textColor = "#FAFAFA"
secondaryBackgroundColor = "#262730"
font = "sans serif"
